spring.application.name=Project2

# ================= DATABASE =================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/mydb2}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

# ================= JPA =================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ================= THYMELEAF =================

spring.thymeleaf.cache=false

# ================= FILE UPLOAD =================

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ================= SERVER =================

server.port=${PORT:8080}